### ISSUE TITLE
Bluetooth TODO

### ISSUE THREAD

**Issue by ajayyy** [LakeEffectRobotics/LakeEffectScoutingApp#4]
## Sending Fixes And Improvements
- [x] Change name line 153 MainActivity
- [x] Line 229 MainActivity Connected Code commented out?
- [x] Line 365 Main Activity duplicate adding to pending messages?
- [x] Make pending messages save to prefrences for later use (after closing app)

- [x] Make it remove from shared preference too

- [x] Make pending messages added, then removed only when done is sent, not added then

- [x] are pending messages working?  line 175 Server app used to be `in.read(bytes, 0, 0)` and now is `in.read(bytes)`, so it should work

## Switching Which App Is The Server
- [x] Make Scouting Input App the server
- [x] http://stackoverflow.com/a/7938949/1985387
- [x] http://stackoverflow.com/a/17355459/1985387
- [x] http://stackoverflow.com/a/15945009/1985387

## To Pair With Device Automatically

- [x] https://github.com/lorensiuswlt/AndroBluetooth/blob/master/src/net/londatiga/android/bluetooth/MainActivity.java#L187
- [x] register that receiver   https://github.com/lorensiuswlt/AndroBluetooth/blob/master/src/net/londatiga/android/bluetooth/MainActivity.java#L123
- [x] to pair https://github.com/lorensiuswlt/AndroBluetooth/blob/master/src/net/londatiga/android/bluetooth/DeviceListActivity.java#L76
- [x] Other info http://www.londatiga.net/it/programming/android/how-to-programmatically-pair-or-unpair-android-bluetooth-device/

## For Server To Be Always Visible

- [x] http://stackoverflow.com/a/29182157/1985387

@Aree-Vanier
